FROM julia:1.4

WORKDIR /usr/logger/
ENV JULIA_PROJECT=/usr/logger/

COPY Project.toml /usr/logger/Project.toml
COPY Manifest.toml /usr/logger/Manifest.toml

RUN julia -e 'using Pkg; Pkg.instantiate()'

COPY src/*.jl /usr/logger/src/

RUN julia -e 'using Pkg; Pkg.status()'

CMD ["julia", "-v"]
