version: "3"

volumes:
    # pg_db_data:
    # influx_db_data:
    # influx_db_conf:
    log_data:
    julia_cache:

networks:
    dumbhome_default:
        external: true

services:

    logger:
        build:
            context: .
            dockerfile: Dockerfile-logger
        working_dir: /usr/logger
        command: ./wait-for-it.sh socat:58100 -s -- ./wait-for-it.sh pigpiod:8888 -s -- ./wait-for-it.sh db:8086 -s -- julia -O3 src/SmartyLogger.jl
        restart: unless-stopped
        env_file:
            - "logger.env"
        depends_on:
            - "pigpiod"
            - "socat"
            # - "influx_db"
        volumes:
            - "log_data:/usr/logger/log"
            - "julia_cache:/root/.julia"
        networks:
            - default
            - dumbhome_default

    socat:
        build:
            context: .
            dockerfile: Dockerfile-socat
        command: socat -d -d TCP-LISTEN:58100,reuseaddr,fork file:/dev/ttyAMA0,b115200,raw,echo=0
        restart: unless-stopped
        devices:
            - "/dev/ttyAMA0:/dev/ttyAMA0"

    pigpiod:
        build:
            context: .
            dockerfile: Dockerfile-pigpiod
        privileged: true
        restart: unless-stopped
        devices:
            - "/dev/gpiomem:/dev/gpiomem"

    # pg_db:
    #     image: postgres
    #     restart: unless-stopped
    #     ports:
    #         - "5432"
    #     volumes:
    #         - "pg_db_data:/var/lib/postgresql/data"

    # db:
    #     image: influxdb
    #     restart: unless-stopped
    #     ports:
    #         - "8086"
    #         - "8088"
    #         - "18089/udp"
    #     volumes:
    #         - influx_db_data:/var/lib/influxdb/
    #         - influx_db_conf:/etc/influxdb/

    # ping:
    #     image: debian
    #     command: ping db
    #     networks:
    #         - default
    #         - dumbhome_default
