FROM debian:stretch

RUN apt-get update && apt-get install -y build-essential curl

RUN curl -L https://github.com/joan2937/pigpio/archive/V68.tar.gz | tar xvz \
  && cd pigpio-68 \
  && make install

EXPOSE 8888

CMD ["pigpiod", "-g"]
