version: "3"

volumes:
    log_data:
    julia_cache:

services:

    logger:
        build:
            context: .
            dockerfile: Dockerfile-logger
        working_dir: /usr/logger/
        command: julia src/SmartyLogger.jl
        restart: "unless-stopped"
        env_file:
            - "logger.env"
        volumes:
            - "log_data:/usr/logger/log"
            - "julia_cache:/root/.julia"
        network_mode: bridge
        external_links:
            - influxdb
            - mqtt-broker
